name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          mkdir tests/langservers
      - run: |
          cd tests/langservers && npm install javascript-typescript-langserver pyright
      - shell: bash
        run: |
          cd tests/langservers
          wget "https://github.com/clangd/clangd/releases/download/19.1.2/clangd-linux-19.1.2.zip"
          python3 -m zipfile -e "clangd-linux-19.1.2.zip" .
          chmod +x clangd_19.1.2/bin/clangd
        
        # TODO: go fails to install
      #      - name: Install Go
      #        uses: actions/setup-go@v2
      #        with:
      #          go-version: 1.16.x
      #      - run: |
      #          cd tests/langservers && GOPATH="$(pwd)" GO111MODULE=on go get golang.org/x/tools/gopls@latest
      - run: |
          pip install poetry && poetry install
      - run: |
          poetry run pytest --cov=sansio_lsp_client --cov-report=xml:cov.xml -v
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: cov.xml